// Code generated by Kitex v0.5.1. DO NOT EDIT.

package leafservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	leaf "github.com/xince-fun/FreeMall/kitex_gen/leaf"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GenSegmentId(ctx context.Context, request *leaf.IdRequest, callOptions ...callopt.Option) (r *leaf.IdResponse, err error)
	GenSnowflakeId(ctx context.Context, request *leaf.IdRequest, callOptions ...callopt.Option) (r *leaf.IdResponse, err error)
	DecodeSnowflakeId(ctx context.Context, request *leaf.DecodeSnokflakeRequest, callOptions ...callopt.Option) (r *leaf.DecodeSnokflakeResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kLeafServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLeafServiceClient struct {
	*kClient
}

func (p *kLeafServiceClient) GenSegmentId(ctx context.Context, request *leaf.IdRequest, callOptions ...callopt.Option) (r *leaf.IdResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenSegmentId(ctx, request)
}

func (p *kLeafServiceClient) GenSnowflakeId(ctx context.Context, request *leaf.IdRequest, callOptions ...callopt.Option) (r *leaf.IdResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenSnowflakeId(ctx, request)
}

func (p *kLeafServiceClient) DecodeSnowflakeId(ctx context.Context, request *leaf.DecodeSnokflakeRequest, callOptions ...callopt.Option) (r *leaf.DecodeSnokflakeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DecodeSnowflakeId(ctx, request)
}
