version: '3'

# 项目启动的依赖，启动项目之前要先启动此环境

services:
  mysql:
    image: mysql/mysql-server:8.0.28-aarch64
    container_name: mall-mysql
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # root密码
      MYSQL_ROOT_PASSWORD: M0I7N1G5MALL
    ports:
      - "33069:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      # Modify the Mysql 8.0 default password strategy to the original strategy (MySQL8.0 to change its default strategy will cause the password to be unable to match)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    restart: always
    networks:
      - free_mall_net

  # redis
  redis:
    image: redis:6.2.6-alpine
    container_name: mall-redis
    ports:
      - "36379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/data:/data:rw
    command: "redis-server --requirepass M0I7N1G5MALL --appendonly yes"
    privileged: true
    restart: always
    networks:
      - free_mall_net

  # ETCD
  Etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"

networks:
  free_mall_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16