// Code generated by hertz generator. DO NOT EDIT.

package hertz_router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	leaf "github.com/xince-fun/FreeMall/app/api/hertz_router/leaf"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	leaf.Register(r)
}
