// Code generated by hertz generator.

package leaf

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gensegmentidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _snowflakeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _decodesnowflakeidMw() []app.HandlerFunc {
	// your code...
	return nil
}
